// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {security} from '../models';

export function AddAttachment(arg1:string,arg2:string,arg3:string):Promise<domain.Attachment>;

export function BulkUpdateHoldingUnits(arg1:domain.BulkUpdateHoldingUnitsRequest):Promise<void>;

export function ChangePIN(arg1:string,arg2:string):Promise<void>;

export function CheckForUpdates():Promise<domain.UpdateCheckResult>;

export function CreateBackup(arg1:string):Promise<security.BackupManifest>;

export function CreateInvestment(arg1:domain.CreateInvestmentRequest):Promise<string>;

export function DeleteAttachment(arg1:string):Promise<void>;

export function DeleteHoldingUnit(arg1:string):Promise<void>;

export function ExportRecoveryKey(arg1:string):Promise<string>;

export function GetAllocationBreakdown():Promise<domain.AllocationBreakdown>;

export function GetAppVersion():Promise<string>;

export function GetAttachmentBytes(arg1:string):Promise<domain.AttachmentBytes>;

export function GetDateFormatPattern():Promise<string>;

export function GetHoldingsFilterOptions():Promise<domain.HoldingsFilterOptions>;

export function GetLatestPrices():Promise<domain.SpotQuote>;

export function GetMetalAverageCosts():Promise<Array<domain.MetalAverageCost>>;

export function GetMonthlyBreakdown(arg1:string,arg2:string):Promise<Array<domain.MonthlyMetalBreakdown>>;

export function GetMonthlyPage(arg1:string,arg2:string):Promise<domain.MonthlyPage>;

export function GetPnLContribution(arg1:string,arg2:string):Promise<domain.PnLContributionReport>;

export function GetPortfolioHistory(arg1:string,arg2:string):Promise<Array<domain.PortfolioHistoryPoint>>;

export function GetPortfolioSummary():Promise<domain.PortfolioSummary>;

export function GetPortfolioValueAt(arg1:string):Promise<domain.PortfolioValueAt>;

export function GetSettings():Promise<domain.AppSettings>;

export function GetUnit(arg1:string):Promise<domain.UnitValuation>;

export function InstallUpdate():Promise<void>;

export function IsUnlocked():Promise<boolean>;

export function ListAttachments(arg1:string,arg2:string):Promise<Array<domain.Attachment>>;

export function ListDealerSummaries():Promise<Array<domain.DealerSummary>>;

export function ListGroupedHoldings(arg1:domain.HoldingsFilter):Promise<Array<domain.GroupedHolding>>;

export function ListRecentlyDeleted():Promise<Array<domain.UnitValuation>>;

export function ListSoldArchive(arg1:domain.HoldingsFilter):Promise<Array<domain.UnitValuation>>;

export function ListUnitsInGroup(arg1:string):Promise<Array<domain.UnitValuation>>;

export function Lock():Promise<void>;

export function PreviewWhatIf(arg1:domain.WhatIfRequest):Promise<domain.WhatIfPreview>;

export function PurgeHoldingUnit(arg1:string):Promise<void>;

export function RecoverWithKey(arg1:string,arg2:string):Promise<void>;

export function RestoreBackup(arg1:string,arg2:boolean):Promise<security.BackupManifest>;

export function RestoreHoldingUnit(arg1:string):Promise<void>;

export function SaveAttachment(arg1:string):Promise<void>;

export function SaveRecoveryKit(arg1:string):Promise<void>;

export function SaveRecoveryKitFromKey(arg1:string):Promise<void>;

export function SellUnit(arg1:domain.SellUnitRequest):Promise<void>;

export function SellUnits(arg1:domain.SellUnitsRequest):Promise<void>;

export function SetupVault(arg1:string):Promise<security.SetupResult>;

export function TouchActivity():Promise<void>;

export function Unlock(arg1:string):Promise<void>;

export function UpdateHoldingUnit(arg1:domain.UpdateHoldingUnitRequest):Promise<void>;

export function UpdateSettings(arg1:domain.AppSettings):Promise<void>;

export function VaultExists():Promise<boolean>;

export function VerifyBackup(arg1:string):Promise<security.BackupVerifyResult>;
