// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAttachment(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddAttachment'](arg1, arg2, arg3);
}

export function BulkUpdateHoldingUnits(arg1) {
  return window['go']['main']['App']['BulkUpdateHoldingUnits'](arg1);
}

export function ChangePIN(arg1, arg2) {
  return window['go']['main']['App']['ChangePIN'](arg1, arg2);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function CreateBackup(arg1) {
  return window['go']['main']['App']['CreateBackup'](arg1);
}

export function CreateInvestment(arg1) {
  return window['go']['main']['App']['CreateInvestment'](arg1);
}

export function DeleteAttachment(arg1) {
  return window['go']['main']['App']['DeleteAttachment'](arg1);
}

export function DeleteHoldingUnit(arg1) {
  return window['go']['main']['App']['DeleteHoldingUnit'](arg1);
}

export function ExportRecoveryKey(arg1) {
  return window['go']['main']['App']['ExportRecoveryKey'](arg1);
}

export function GetAllocationBreakdown() {
  return window['go']['main']['App']['GetAllocationBreakdown']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetAttachmentBytes(arg1) {
  return window['go']['main']['App']['GetAttachmentBytes'](arg1);
}

export function GetDateFormatPattern() {
  return window['go']['main']['App']['GetDateFormatPattern']();
}

export function GetHoldingsFilterOptions(arg1) {
  return window['go']['main']['App']['GetHoldingsFilterOptions'](arg1);
}

export function GetLatestPrices() {
  return window['go']['main']['App']['GetLatestPrices']();
}

export function GetMetalAverageCosts() {
  return window['go']['main']['App']['GetMetalAverageCosts']();
}

export function GetMonthlyBreakdown(arg1, arg2) {
  return window['go']['main']['App']['GetMonthlyBreakdown'](arg1, arg2);
}

export function GetMonthlyPage(arg1, arg2) {
  return window['go']['main']['App']['GetMonthlyPage'](arg1, arg2);
}

export function GetPnLContribution(arg1, arg2) {
  return window['go']['main']['App']['GetPnLContribution'](arg1, arg2);
}

export function GetPortfolioHistory(arg1, arg2) {
  return window['go']['main']['App']['GetPortfolioHistory'](arg1, arg2);
}

export function GetPortfolioSummary() {
  return window['go']['main']['App']['GetPortfolioSummary']();
}

export function GetPortfolioValueAt(arg1) {
  return window['go']['main']['App']['GetPortfolioValueAt'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetUnit(arg1) {
  return window['go']['main']['App']['GetUnit'](arg1);
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function IsUnlocked() {
  return window['go']['main']['App']['IsUnlocked']();
}

export function ListAttachments(arg1, arg2) {
  return window['go']['main']['App']['ListAttachments'](arg1, arg2);
}

export function ListDealerSummaries() {
  return window['go']['main']['App']['ListDealerSummaries']();
}

export function ListGroupedHoldings(arg1) {
  return window['go']['main']['App']['ListGroupedHoldings'](arg1);
}

export function ListRecentlyDeleted() {
  return window['go']['main']['App']['ListRecentlyDeleted']();
}

export function ListSoldArchive(arg1) {
  return window['go']['main']['App']['ListSoldArchive'](arg1);
}

export function ListUnitsInGroup(arg1) {
  return window['go']['main']['App']['ListUnitsInGroup'](arg1);
}

export function Lock() {
  return window['go']['main']['App']['Lock']();
}

export function PreviewWhatIf(arg1) {
  return window['go']['main']['App']['PreviewWhatIf'](arg1);
}

export function PurgeHoldingUnit(arg1) {
  return window['go']['main']['App']['PurgeHoldingUnit'](arg1);
}

export function RecoverWithKey(arg1, arg2) {
  return window['go']['main']['App']['RecoverWithKey'](arg1, arg2);
}

export function RestoreBackup(arg1, arg2) {
  return window['go']['main']['App']['RestoreBackup'](arg1, arg2);
}

export function RestoreHoldingUnit(arg1) {
  return window['go']['main']['App']['RestoreHoldingUnit'](arg1);
}

export function SaveAttachment(arg1) {
  return window['go']['main']['App']['SaveAttachment'](arg1);
}

export function SaveRecoveryKit(arg1) {
  return window['go']['main']['App']['SaveRecoveryKit'](arg1);
}

export function SaveRecoveryKitFromKey(arg1) {
  return window['go']['main']['App']['SaveRecoveryKitFromKey'](arg1);
}

export function SellUnit(arg1) {
  return window['go']['main']['App']['SellUnit'](arg1);
}

export function SellUnits(arg1) {
  return window['go']['main']['App']['SellUnits'](arg1);
}

export function SetupVault(arg1) {
  return window['go']['main']['App']['SetupVault'](arg1);
}

export function TouchActivity() {
  return window['go']['main']['App']['TouchActivity']();
}

export function Unlock(arg1) {
  return window['go']['main']['App']['Unlock'](arg1);
}

export function UpdateHoldingUnit(arg1) {
  return window['go']['main']['App']['UpdateHoldingUnit'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function VaultExists() {
  return window['go']['main']['App']['VaultExists']();
}

export function VerifyBackup(arg1) {
  return window['go']['main']['App']['VerifyBackup'](arg1);
}
